Repository PRUNplanner/frontend, pull requests merged in 2025-08, with the labels that each got.

#108 feat(imprint-tos): add imprint and tos
  src/App.vue
  src/features/account/components/LoginComponent.vue
  src/router/index.ts
  src/views/ImprintToSView.vue
Labels: enhancement

#110 feat(marketexploration): skip same trade volumes
  src/features/market_exploration/useMarketExplorationChart.ts
  src/tests/features/market_exploration/useMarketExplorationChart.test.ts
Labels: improvement

#116 fix(marketexploration): sanitize data spikes
  src/features/market_exploration/useMarketExplorationChart.ts
  src/tests/features/market_exploration/useMarketExplorationChart.test.ts
  src/views/market-data/MarketExplorationView.vue
Labels: bug

#118 Add Supply Cart feature with FIO storage integration
  src/features/fio/useFIOStorage.ts
  src/features/planning/components/tools/PlanSupplyCart.vue
  src/features/xit/components/XITTransferActionButton.vue
  src/tests/features/fio/useFIOStorage.test.ts
  src/tests/test_data/api_data_fio_storage.json
  src/views/PlanView.vue
Labels: enhancement

#119 feat(plan): implement construction cart, fix inertClone + tets
  src/features/game_data/useMaterialData.ts
  src/features/planning/components/tools/PlanConstructionCart.vue
  src/features/planning/usePlanCalculation.ts
  src/features/planning/usePlanCalculation.types.d.ts
  src/features/planning/usePlanCalculationPreComputes.ts
  src/stores/planningStore.ts
  src/tests/features/planning/usePlanCalculation.test.ts
  src/tests/stores/planningStore.test.ts
  src/tests/util/data.test.ts
  src/util/data.ts
  src/views/PlanView.vue
Labels: enhancement

#139 fix(plan): delayed plan
  src/features/material_tile/components/MaterialTile.vue
  src/main.ts
Labels: bug

#141 feat(material): cx data popover table
  src/features/cx/components/MaterialCXOverviewTable.vue
  src/features/material_tile/components/MaterialTile.vue
  src/layout/prunplannerNaiveUI.ts
Labels: enhancement

#154 chore(vite): upgrade packages, reduce chunks
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: improvement, dependencies

#145 Introduce a "buy from cx" button for XIT
  src/assets/help/changelog.md
  src/features/xit/components/XITBurnActionButton.vue
  src/features/xit/components/XITTransferActionButton.vue
  src/features/xit/useXITAction.ts
  src/features/xit/xitAction.types.ts
  src/features/xit/xitConstants.ts
  src/tests/features/xit/useXITAction.test.ts
Labels: enhancement

#156 Fix recipe profit calculations to use efficiency
  src/assets/help/changelog.md
  src/features/planning/usePlanCalculation.ts
Labels: bug

#159 feat(resourceoverview): implements resource overview
  src/assets/help/changelog.md
  src/assets/help/tools_resource_roi_overview.md
  src/features/navigation/components/NavigationBar.vue
  src/features/resource_roi_overview/components/ResourceROITable.vue
  src/features/resource_roi_overview/useResourceROIOverview.ts
  src/features/resource_roi_overview/useResourceROIOverview.types.ts
  src/router/index.ts
  src/tests/features/resource_roi_overview/useResourceROIOverview.test.ts
  src/views/HelpView.vue
  src/views/tools/ResourceROIOverviewView.vue
Labels: enhancement

#160 feat(preference): keep user preferred cx uuid
  src/features/exchanges/components/CXPreferenceSelector.vue
  src/features/preferences/usePreferences.ts
  src/features/preferences/userDefaults.ts
  src/features/preferences/userPreferences.types.ts
  src/features/profile/components/UserPreferences.vue
  src/tests/features/preferences/usePreferences.test.ts
  src/views/HelpView.vue
  src/views/ProfileView.vue
Labels: improvement

#162 fix(plan): tool re-rendering
  src/assets/help/changelog.md
  src/features/planning/components/tools/PlanOptimizeHabitation.vue
  src/views/PlanView.vue
Labels: bug

#163 More better material icons
  src/assets/css/materials.css
  src/assets/help/changelog.md
  src/features/material_tile/components/MaterialTile.vue
Labels: improvement

#167 refactor(multiple): split components, adjusts widths/line breaks
  src/assets/help/changelog.md
  src/features/empire/components/EmpireCostOverview.vue
  src/features/empire/components/EmpireMaterialIO.vue
  src/features/empire/components/EmpireMaterialIOFilters.vue
  src/features/empire/components/EmpirePlanList.vue
  src/features/resource_roi_overview/components/ResourceROITable.vue
  src/features/resource_roi_overview/components/ResourceROITableFilters.vue
  src/features/roi_overview/components/ROIOverviewTable.vue
  src/features/roi_overview/components/ROIOverviewTableFilters.vue
  src/views/EmpireView.vue
Labels: improvement

#168 chore(license): add name to license
  LICENSE
Labels: improvement

#170 fix(management): checkbox performance
  src/features/manage/components/ManagePlanEmpireAssignments.vue
  src/layout/components/SimpleCheckbox.vue
Labels: bug

#177 fix(plan): handle plan name on saveability
  src/assets/help/changelog.md
  src/features/planning/usePlanCalculation.ts
  src/features/planning/usePlanCalculationHandlers.ts
Labels: bug

#178 fix(exchange): preference update not persisted
  src/assets/help/changelog.md
  src/lib/apiService.ts
  src/lib/query_cache/queryRepository.ts
  src/stores/planningStore.ts
  src/views/ExchangesView.vue
Labels: bug

#184 feat(build): improve vite build and chunking
  .gitignore
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: refactor

#185 fix(xit): skip 0 value elements in XIT Transfer
  src/assets/help/changelog.md
  src/features/xit/components/XITTransferActionButton.vue
Labels: fix

#188 feat(build): creates a version.json, notifies user
  netlify.toml
  package.json
  scripts/write-version.js
  src/App.vue
  src/assets/help/changelog.md
  src/layout/components/VersionUpdateNotification.vue
  src/lib/useVersionCheck.ts
  src/ui/components/PSelect.vue
  src/ui/components/PSelectMultiple.vue
  vite.config.ts
Labels: feat

#189 improve(test): add useVersionCheck tests
  package.json
  pnpm-lock.yaml
  src/lib/useVersionCheck.ts
  src/tests/lib/useVersionCheck.test.ts
  tsconfig.app.json
  vitest.config.ts
Labels: improve

#194 refactor(tsc): typescheck config, build without tsc
  package.json
  scripts/write-version.js
  tsconfig.app.json
  tsconfig.typecheck.json
Labels: refactor

#195 feat(profile): implements profile
  src/assets/help/changelog.md
  src/features/account/components/VerifyEmailComponent.vue
  src/features/api/schemas/user.schemas.ts
  src/features/api/userData.api.ts
  src/features/api/userData.types.ts
  src/features/profile/components/ChangePassword.vue
  src/features/profile/components/ChangeProfile.vue
  src/features/profile/components/UserPreferences.vue
  src/lib/query_cache/queryRepository.ts
  src/lib/query_cache/queryRepository.types.ts
  src/lib/usePostHog.ts
  src/router/index.ts
  src/tests/features/api/userData.api.test.ts
  src/tests/lib/query_cache/queryStore.test.ts
  src/tests/lib/usePostHog.test.ts
  src/ui/components/PCheckbox.vue
  src/ui/components/PFormSeperator.vue
  src/ui/components/PInput.vue
  src/ui/index.ts
  src/views/ProfileView.vue
  src/views/VerifyEmailView.vue
Labels: feat

#199 feat(ui): add select keyboard navigation
  src/assets/help/changelog.md
  src/ui/components/PSelect.vue
  src/ui/components/PSelectMultiple.vue
Labels: improve

#201 Key-based Backend Communcation, Store persistance & cross-tab broadcasting
  eslint.config.js
  src/assets/help/changelog.md
  src/features/account/components/VerifyEmailComponent.vue
  src/features/empire/components/EmpireConfiguration.vue
  src/features/government/components/PlanetPOPRButton.vue
  src/features/manage/components/ManageCX.vue
  src/features/manage/components/ManageEmpire.vue
  src/features/manage/components/ManagePlanEmpireAssignments.vue
  src/features/market_exploration/useMarketExploration.ts
  src/features/market_exploration/useMarketExplorationChart.ts
  src/features/navigation/components/NavigationBar.vue
  src/features/planet_search/components/PlanetSearchAdvanced.vue
  src/features/planet_search/components/PlanetSearchBasic.vue
  src/features/planning/components/tools/PlanOptimizeHabitation.vue
  src/features/planning/components/tools/PlanPOPR.vue
  src/features/planning_data/usePlan.ts
  src/features/profile/components/ChangePassword.vue
  src/features/profile/components/ChangeProfile.vue
  src/features/resource_roi_overview/useResourceROIOverview.ts
  src/features/sharing/useSharing.ts
  src/features/wrapper/useGameDataLoader.ts
  src/features/wrapper/usePlanningDataLoader.ts
  src/lib/piniaBroadcastChannelPlugin.ts
  src/lib/query_cache/QueryCacheView.vue
  src/lib/query_cache/queryCache.types.ts
  src/lib/query_cache/queryRepository.ts
  src/lib/query_cache/queryRepository.types.ts
  src/lib/query_cache/queryStore.ts
  src/lib/query_cache/useQuery.ts
  src/main.ts
  src/stores/gameDataStore.ts
  src/stores/planningStore.ts
  src/tests/lib/query_cache/queryStore.test.ts
  src/tests/stores/planningStore.test.ts
  src/ui/components/PInputNumber.vue
  src/views/EmpireView.vue
  src/views/ExchangesView.vue
  src/views/tools/HQUpgradeCalculatorView.vue
  src/views/tools/market-data/MarketExplorationView.vue
  vitest.config.ts
Labels: feat

#203 feat(productionchain): Implements the Production Chain tool incl. analysis / coloring as known from v1
  package.json
  pnpm-lock.yaml
  src/assets/help/changelog.md
  src/assets/help/tools_production_chain.md
  src/features/game_data/useBuildingData.ts
  src/features/game_data/useMaterialData.ts
  src/features/navigation/components/NavigationBar.vue
  src/features/production_chain/components/ChainNode.types.ts
  src/features/production_chain/components/ChainNode.vue
  src/features/production_chain/components/GraphAnalysisExpertise.vue
  src/features/production_chain/components/GraphAnalysisMaterials.vue
  src/features/production_chain/components/GraphAnalysisWorkforce.vue
  src/features/production_chain/components/GraphVueFlow.vue
  src/features/production_chain/dagre.config.ts
  src/features/production_chain/productionEdge.ts
  src/features/production_chain/productionGraph.ts
  src/features/production_chain/productionGraph.types.ts
  src/features/production_chain/productionNode.ts
  src/features/production_chain/useGraph.ts
  src/router/index.ts
  src/tests/features/game_data/useMaterialData.test.ts
  src/tests/features/production_chain/dagre.config.test.ts
  src/tests/features/production_chain/productionEdge.test.ts
  src/tests/features/production_chain/productionGraph.test.ts
  src/tests/features/production_chain/productionNode.test.ts
  src/tests/features/production_chain/useGraph.test.ts
  src/ui/components/PSelect.vue
  src/views/tools/ProductionChainView.vue
Labels: feat

#206 improve(versioncheck): skip if user is not logged in
  src/App.vue
  src/assets/help/changelog.md
  src/lib/useVersionCheck.ts
  src/stores/userStore.ts
  src/tests/lib/useVersionCheck.test.ts
Labels: improve

#212 improve(indexeddb): have preload called after queries
  src/App.vue
  src/AppProvider.vue
  src/database/composables/useDB.ts
  src/database/composables/useIndexedDBStore.ts
  src/database/services/useMaterialData.ts
  src/database/services/usePlanetData.ts
  src/database/stores.ts
  src/features/empire/components/EmpireAnalysis.vue
  src/features/exchanges/useManageCX.ts
  src/features/hq_upgrade_calculator/useHQUpgradeCalculator.ts
  src/features/material_tile/components/MaterialTile.vue
  src/features/planning/components/tools/PlanConstructionCart.vue
  src/features/planning/util/materialIO.util.ts
  src/features/production_chain/components/ChainNode.vue
  src/features/production_chain/productionGraph.ts
  src/features/xit/components/XITBurnActionButton.vue
  src/features/xit/useBurnXITAction.ts
  src/lib/query_cache/queryRepository.ts
  src/tests/database/services/useMaterialData.test.ts
  src/tests/features/xit/useXITBurnAction.test.ts
  src/views/tools/market-data/MarketExplorationView.vue
Labels: improve

#213 fix(roi): prevent parallel mutation, improve(hq): use vue computed instead of watcheffect
  src/assets/help/changelog.md
  src/features/hq_upgrade_calculator/useHQUpgradeCalculator.ts
  src/features/roi_overview/components/ROIOverviewTable.vue
  src/features/roi_overview/useROIOverview.ts
  src/tests/features/hq_upgrade_calculator/useHQUpgradeCalculator.test.ts
  src/tests/util/data.test.ts
  src/util/data.ts
Labels: fix, improve

#215 feat(calculations): parallel calculation, visual indication
  src/assets/help/changelog.md
  src/features/planet_search/components/PlanetSearchResults.vue
  src/features/resource_roi_overview/useResourceROIOverview.ts
  src/features/roi_overview/components/ROIOverviewTable.vue
  src/features/roi_overview/useROIOverview.ts
  src/layout/components/ComputingProgress.vue
  src/ui/components/PProgressBar.vue
  src/ui/index.ts
  src/views/EmpireView.vue
  src/views/fio/FIOBurnView.vue
  src/views/tools/ResourceROIOverviewView.vue
Labels: feat, improve
